### PR TITLE
Fix UI freeze when searching

### LINKED ISSUE #187: Text search freezes UI
Follow up on https://github.com/eclipse-platform/eclipse.platform.text/issues/186

This seem to be a regression **after** 4.25.

I can't reproduce on 4.25 but I can reproduce on master / SDK-I20230426-1800-linux-gtk-x86_64.

In my workspace that contains most of SDK bundles as sources case-insensitive searching for "a" in all files freezes UI after roughly 1.000.000 matches and at 2%, staying in that state with 100% CPU load for minutes. 
I have to kill IDE because it become not responsible.

In my (other and bigger) workspace on 4.25 search takes few seconds to find 26.000.000 matches without any freeze.

In the jstacks I see `AbstractTextSearchResult.getMatchCount()` that is almost always on top

```
"main" #1 prio=6 os_prio=0 cpu=538026.91ms elapsed=20829.88s tid=0x00007ffff0028f70 nid=0x9676 runnable  [0x00007ffff7fb6000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap$Traverser.advance(java.base@17.0.6-internal/ConcurrentHashMap.java:3383)
	at java.util.concurrent.ConcurrentHashMap$ValueIterator.next(java.base@17.0.6-internal/ConcurrentHashMap.java:3483)
	at org.eclipse.search.ui.text.AbstractTextSearchResult.getMatchCount(AbstractTextSearchResult.java:305)
	at org.eclipse.search.internal.ui.text.FileTreeContentProvider.getMatchCount(FileTreeContentProvider.java:189)
	at org.eclipse.search.internal.ui.text.FileTreeContentProvider.elementsChanged(FileTreeContentProvider.java:239)
	- locked <0x0000000456e67178> (a org.eclipse.search.internal.ui.text.FileTreeContentProvider)
	at org.eclipse.search.internal.ui.text.FileSearchPage.elementsChanged(FileSearchPage.java:343)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.runBatchedUpdates(AbstractTextSearchViewPage.java:1263)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage$UpdateUIJob.runInUIThread(AbstractTextSearchViewPage.java:154)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.ui.progress.UIJob$$Lambda$725/0x00000008012bee70.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	- locked <0x0000000454260438> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
```

### PR DESCRIPTION
**Pull request by jjohnstn**
- add filtering to FileTreeContentProvider.elementsChanged() method so extraneous line elements are already filtered out of lineMatches set
- fixes #187

### CODE REVIEW

**Comment by jjohnstn** [comment]
@iloveeclipse This is the other solution

**Comment by iloveeclipse** [comment]
Jeff, I honestly have no idea what filters should filter in the patch (may be a comment in the code would help) and additionally I have no IDE access till weekend, so can't even debug or verify anything.

**Comment by jjohnstn** [comment]
@iloveeclipse I'll add a comment.  The filter is set up to eliminate the same match being reported to two projects (one being nested in the other).  The filter takes a FileMatch input and decides if it is being reported on the innermost project.  The stream I am changing already is taking FileMatches and getting the line matches.  In the loop, I was eventually seeing if the line match should be filtered because it's matched file is an outer duplicate.  The count isn't relevant, it is whether the reported resource matches should be filtered.  I have moved the check up so the line matches are already cleared.  No count required and the filtering check is quick at this point.  I could make it even quicker by checking for the filter length and doing one of two calculations of the line matches where one does filter checking and the other doesn't.

I have verified that my solution continues to filter out duplicates in the file search results.  I'm sure yours will do the same.

Will either solution be able to be put into 4.28 M2?  I can't

**Comment by iloveeclipse** [comment]
I would favor yours, since you know what the code is doing, and I just had some minutes between meetings to look at it :)
Please add comments to the code and I can merge.

**Comment by jjohnstn** [comment]
@iloveeclipse Let me know if the comment is ok.  I added the check for active filters so the logic behaves exactly as it did before and should match or exceed the performance of #188.

**Comment by iloveeclipse** [comment]
Jeff, the whole elementsChanged() code wasn't easy to understand and filtering added on top didn't make it easier. 
Your comment before on this PR explained things better - xould you please add something lile this to the javadoc of elementsChanged()?

**Comment by iloveeclipse** [comment]
Thanks Jeff!

**Pull request merged**
