### PR TITLE
Add updateRelease.yml

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@laeubi Any idea what went wrong in https://github.com/akurtakov/eclipse.platform.text/actions/runs/4352345143/jobs/7605013788 ?

**Comment by akurtakov** [comment]
I get what is wrong - it tries git add **/pom.xml but everything is pomless so updateRelease.yml needs a change.

**Comment by laeubi** [comment]
@akurtakov the problem is that I don't have enough git-power to get something that includes ANY `pom.xml` (including the root!) so i used two path specs but it seems git for some reason don'T like that .... its a bit of a mystery to me ;-)

**Comment by laeubi** [comment]
> I'll push the change as the fix to the action has to go in the action repo itself.

You can also use a forked "releng" repo for experiments with the "included" workflow :-)

**Comment by akurtakov** [comment]
It is probably bailing on first issue and not even trying next.

**Comment by laeubi** [comment]
Yes probabbly but we already have had sucessfull runs, so its a bit confusing (for me), so if you can suggest a more gracefull pattern that would be great!

**Pull request merged**
