### PR TITLE
Fix NPE when searching in open file which is linked multiple times

### PR DESCRIPTION
**Pull request by jukzi**
see https://github.com/eclipse-platform/eclipse.platform.text/pull/30#issuecomment-1185512753

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
This change looks good and fixed the NPE for me in the reproducible case you mentioned.

Thank you!

**Comment by HannesWell** [comment]
M2 Stabilization starts on Tuesday midnight.
So if you are fine with this as well and want it in M2, it can be merged until Monday 23:59.

**Comment by jukzi** [comment]
thanks @HannesWell for reporting and testing it too.

**Comment by HannesWell** [comment]
Thank you for fixing this :)

**Pull request merged**
