### PR TITLE
Minimap can cause NPE #69

### PR DESCRIPTION
**Pull request by GeraldMit**
fix Minimap can cause NPE #69

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@GeraldMit : thanks for the patch.

- Please avoid working on master branch, merge commits and partial commits.
- For such small issue PR should have one commit with appropriate commit message referencing existing issue #69 or explaining in commit message what is supposed to be fixed.
- See detailed description https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md

So for now:

- create local branch on top of origin master branch
- cherry pick your changes from your master on the new branch
- squash all your commits to one providing appropriate commit message
- push to your fork in github and create new PR.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by GeraldMit** [comment]
> @GeraldMit : thanks for the patch.
> 
> * Please avoid working on master branch, merge commits and partial commits.
> * For such small issue PR should have one commit with appropriate commit message referencing existing issue [Minimap can cause NPE #69](https://github.com/eclipse-platform/eclipse.platform.text/issues/69) or explaining in commit message what is supposed to be fixed.
> * See detailed description https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md
> 
> So for now:
> 
> * create local branch on top of origin master branch
> * cherry pick your changes from your master on the new branch
> * squash all your commits to one providing appropriate commit message
> * push to your fork in github and create new PR.

Unfortunately, no access to a development environment that I can run git/EGit/VSCode on at the moment, and GitHub web doesn't have cherrypicking support. Will have to wait a few days.

**Comment by GeraldMit** [comment]
will open new pull request

**Pull request closed without merging**
