### PR TITLE
Improve FileSearch performance (fixes #29)

### LINKED ISSUE #29: Filesearch: each file is read twice
Search could be improved: The file content should be cached:
image

### PR DESCRIPTION
**Pull request by jukzi**
* Read each file only once (if it fits in the buffers) => ~ 30% faster

* Immediate report search result while still searching => faster visible

* Share workload between threads to avoid that single job with huge file
is running much longer then the others => faster finished.

* Set current filename as job name => better progress report.

### CODE REVIEW

**Comment by mickaelistria** [comment]
This change seems to introduce some risk on a core feature and is IMO not safe enough to put it in RC1. OK to move it to 4.25 M1 ?

**Comment by iloveeclipse** [comment]
> This change seems to introduce some risk on a core feature and is IMO not safe enough to put it in RC1. OK to move it to 4.25 M1 ?

This is neither a bug fix for an urgent issue nor something that was broken recently, so 4.24 is surely wrong anyway.

**Comment by jukzi** [comment]
sure this can wait for M1

**Comment by HannesWell** [comment]
After I upgraded to 4.25 M1 today I got the following reproducible error for the first time when searching the workspace.
I searched for the simple string `PublicKey` using the file name pattern `*.java`. All other options are disabled.

```
java.lang.NullPointerException
	at org.eclipse.search.internal.core.text.TextSearchVisitor$ReusableMatchAccess.getFileContentLength(TextSearchVisitor.java:125)
	at org.eclipse.search.internal.ui.text.FileSearchQuery$TextSearchResultCollector.getLineElement(FileSearchQuery.java:131)
	at org.eclipse.search.internal.ui.text.FileSearchQuery$TextSearchResultCollector.lambda$0(FileSearchQuery.java:97)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at org.eclipse.search.internal.ui.text.FileSearchQuery$TextSearchResultCollector.acceptPatternMatch(FileSearchQuery.java:94)
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.processFile(TextSearchVisitor.java:234)
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.run(TextSearchVisitor.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I suspect this is connected to the associated PR.
Nevertheless the search is very faster now 👍🏽

**Comment by jukzi** [comment]
> After I upgraded to 4.25 M1 today I got the following reproducible error for the first time when searching the workspace.

Please attach "the workspace" or a minimal workspace where the error occurs. i can not reproduce in my workspace.

**Comment by HannesWell** [comment]
> > After I upgraded to 4.25 M1 today I got the following reproducible error for the first time when searching the workspace.
> 
> Please attach "the workspace" or a minimal workspace where the error occurs. i can not reproduce in my workspace.

It was in my workspace that only contains the [Eclipse-Passage Project](https://github.com/eclipse-passage/passage) and was provisioned via their Oomph setup.

Unfortunately I cannot reproduce it anymore either.

But from looking at the code and with the Exception-Stacktrace, I think the only way this could happened is if in `TextSearchJob.processFile()` the `charsequence` String is null, which is the case if `getOpenDocument()` returns not null?

**Comment by jukzi** [comment]
i guess
```
diff --git a/org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java b/org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java
index 5764f60..ec55207 100644
--- a/org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java
+++ b/org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java
@@ -205,13 +205,13 @@
 				}
 
 				List<TextSearchMatchAccess> occurences;
-				CharSequence charsequence = null;
+				CharSequence charsequence;
 
 				IDocument document= getOpenDocument(file, getDocumentsInEditors());
 				if (document != null) {
-					DocumentCharSequence documentCharSequence = new DocumentCharSequence(document);
+					charsequence = new DocumentCharSequence(document);
 					// assume all documents are non-binary
-					occurences = locateMatches(file, documentCharSequence, matcher, monitor);
+					occurences = locateMatches(file, charsequence, matcher, monitor);
 				} else {
 					try {
 						charsequence = fileCharSequenceProvider.newCharSequence(file);

```
would fix that, but i would like to have a situation to test it  - A file open in a text editor linked two times into the workspace? i tried with JDTs org.eclipse.jdt.internal.compiler.lookup.AnnotationHolder but could not reproduce.

**Comment by iloveeclipse** [comment]
> A file open in a text editor linked two times into the workspace?

May be file from nested projects, or from linked virtual folder? There are few legal ways to have same resource appearing multiple times int the workspace.

**Comment by jukzi** [comment]
can reproduce when i link a file external of workspace 2 times and have "both" file editors open.

**Pull request merged**
