### PR TITLE
Run the build on CentOS 9

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Note that on centos-9, we could switch the tests to use wayland

**Comment by akurtakov** [comment]
There would be no centos9 as per https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2827#note_1092972

**Comment by akurtakov** [comment]
Maybe we can switch to ubuntu latest and try using wayland.

**Comment by mickaelistria** [comment]
An alternative would be to define our own containers to use for CI, like it's done for wildwebdeveloper.

**Pull request closed without merging**
